### ISSUE TITLE
我在使用时出现报错ERROR: region can't be empty

### ISSUE THREAD

**Issue by jpx1024** [justjavac/certbot-dns-aliyun#10]
我使用aliyun configure配置了区域ID但仍然无法执行成功。
`
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Simulating a certificate request for *.xxxx.art
Hook '--manual-auth-hook' for xxx.art ran with error output:
 ERROR: region can't be empty
 
 Configuration failed, use `aliyun configure` to configure it
 

Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
  Domain: xxx.art
  Type:   dns
  Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.xxx.art - check that a DNS record exists for this domain

Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

Hook '--manual-cleanup-hook' for xxx.art reported error code 3
Hook '--manual-cleanup-hook' for xxx.art ran with error output:
 ERROR: region can't be empty
 
 Configuration failed, use `aliyun configure` to configure it
 ERROR: region can't be empty
 
 Configuration failed, use `aliyun configure` to configure it
 
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
`

**Comment by justjavac** [comment]
https://help.aliyun.com/document_detail/121258.html?spm=a2c4g.110341.0.0.3b396843xATDwf

配置完成后，若配置凭证有效，显示如下信息：

```
Configure Done!!!
..............888888888888888888888 ........=8888888888888888888D=..............
...........88888888888888888888888 ..........D8888888888888888888888I...........
.........,8888888888888ZI: ...........................=Z88D8888888888D..........
.........+88888888 ..........................................88888888D..........
.........+88888888 .......Welcome to use Alibaba Cloud.......O8888888D..........
.........+88888888 ............. ************* ..............O8888888D..........
.........+88888888 .... Command Line Interface(Reloaded) ....O8888888D..........
.........+88888888...........................................88888888D..........
..........D888888888888DO+. ..........................?ND888888888888D..........
...........O8888888888888888888888...........D8888888888888888888888=...........
............ .:D8888888888888888888.........78888888888888888888O ..............
```

**Comment by justjavac** [comment]
运行 `aliyun configure list` 看看是否已经配置

**Comment by justjavac** [comment]
或者使用阿里云 cli 试一下功能是否正常 https://help.aliyun.com/document_detail/122115.html?spm=a2c4g.122114.0.0.460d6c77Y8hfh4

**Comment by yztz** [comment]
certbot 使用 sudo 运行，而 aliyun cli 没有使用 sudo 配置导致其不能读取存储于 ~/.aliyun 下的配置文件，看看是不是这个原因？

**Comment by jonahfang** [comment]
我也遇到同样的问题。 `aliyun ecs DescribeInstances --dryrun`是成功的，就是报告: ERROR: region can't be empty

**Comment by NicholasStone** [comment]
> certbot 使用 sudo 运行，而 aliyun cli 没有使用 sudo 配置导致其不能读取存储于 ~/.aliyun 下的配置文件，看看是不是这个原因？

我把 ~/.aliyun/config.json 复制到 /root/.aliyun 里面再运行命令就可以正常过了
