### ISSUE TITLE
aliyun configure 显示region不能为空

### ISSUE THREAD

**Issue by supzhang** [justjavac/certbot-dns-aliyun#17]
使用时一直提示如下：Configuration failed, use `aliyun configure` to configure it
 ERROR: region can't be empty   ，可我确定配置了region，不管是cn-hangzhou,cn-beijing,cn-qingdao，None...全部不起作用。

**Comment by justjavac** [comment]
https://github.com/justjavac/certbot-dns-aliyun/issues/10
